### ISSUE TITLE
Bootstrap codebase

### ISSUE THREAD

**Issue by pwalsh** [openspending/fiscal-data-packager#1]
# Description

Our basic bootstrap of express app, jscs code style review, shippable CI, core dependencies, gulp, etc.

The Ebola tracker probably has the most up-to-date implementation right now: https://github.com/okfn/opentrials-ebola-tracker

# Tasks

* [x] core dependencies and dev deps.
* [x] starter gulp file
* [x] jscs config
* [x] the core npm run {command} commands
* [x] shippable integration
* [x] basic, passing test stub
* [x] code coverage integration
* [x] simple express route stub for home page

**Comment by pwalsh** [comment]
DONE.
