### ISSUE TITLE
Handle large(r) files

### ISSUE THREAD

**Issue by pwalsh** [openspending/fiscal-data-packager#12]
# Description

Large files currently don't work in step 1. We are using `papaparse` so that we can handle large files using the features it provides (streaming, processing in web workers, take samples from larger files).

My tests with a [50MB file](https://github.com/os-data/boost-moldova/blob/master/data/boost-moldova.csv), loading it both as a URL and also a downloaded copy of it as a local file upload, shows:

* The user is alerted that the file is processing
* The processing hangs with no visible error in the console for quite some time
* Eventually, we get a 503 error from the goodtables web service, an error raised from the `fetch` promise when GoodTables is called. **However**, A file of this size can be handled by GoodTables. [Here is a URL that will validate this same file directly against the GoodTables API and show the results on the GoodTables web app](http://goodtables.okfnlabs.org/reports?data_url=https%3A%2F%2Fraw.githubusercontent.com%2Fos-data%2Fboost-moldova%2Fmaster%2Fdata%2Fboost-moldova.csv&format=csv&encoding=&schema_url=) 

# Tasks

* [x] If there is a file size limit that gets too hard to handle for whatever reason, we need to throw and alert the user. However, 50MB should be something we aim to handle here - even up to 100MB I'd want to be able to handle
* [x] Specifically, investigate what is causing this to error, and work on a solution for handling files of this size
* [x] Write functional tests for this scenario

**Comment by kravets-levko** [comment]
Since we are using Papa Parse, it allows to read only part of file without loading whole file into memory. Currently it reads 1000 rows, and this is few megabytes of data. So, while we are using this library with some limit for rows, there will not be any issues with data handling.

**Comment by pwalsh** [comment]
FIXED.
