### ISSUE TITLE
Iterate on data type/format and concept implementation of step 2 

### ISSUE THREAD

**Issue by pwalsh** [openspending/fiscal-data-packager#15]
# Description

We simplified the implementation around data types, formats and concepts for the first iteration of step 2. We'll do a number of iterations on this until we get to a UX implementation that fully supports our goals, and the capabilities of Fiscal Data Package mapping.

# Tasks

* [x] The user can change an inferred type for any column. When a user changes an inferred type:
  * [x] Recheck that the column is actually of this type (can take a sample of one value and check)
  * [x] If the user has selected a type that is invalid, don't allow the change, and show the user an error message for her action
* [x] By default, almost all values will be inferred by `jsontableschema.infer` as integers or strings. However, we want to be more precise on this, updating the type based on concepts the user chooses.
  * [x] When the user selects a `concept`, update the `type` to that which matches the concept
  * [x] If the user has selected a concept that leads to an invalid type, don't allow the change, and show the user an error message for her action
  * [x] Type <-> Concept mapping
    * [x] Amount <-> Decimal 
* [x] The output mapping objects, which are dimensions, should all have a `dimensionType` property

**Comment by kravets-levko** [comment]
PR https://github.com/openspending/fiscal-data-packager/pull/31

@pwalsh I decided to implement this without showing any dialogs to users. Current idea is:
1. Detect set of possible types for each column (based on few first rows). That automatically implements first three items of this task - user cannot select invalid type for column. Also, inferred type will be present in this list because `jsontableschema` used to create that list. Also, situation when list is empty is impossible - at least `string` type will be present.
2. Each concept (as object in the app) has a list of possible data types for this concept. So, for each column create list of concepts based on allowed types for this columns. So now user cannot select invalid concept for column.
3. And the last thing - when user selects a concept for column, update type for this column *and* restrict list of allowed types. So, now user can select only type that is allowed for data in this column *and* for selected concept. When user deselects concept, list of types (and column type) is also reset to previous state.

This three things allows always get valid combinations for column type and concept, and I hope it will be easy to user to understand what is happening in the app. Also, I need your opinion about that (when you try it :)

**Comment by pwalsh** [comment]
@kravets-levko looks great!
