### ISSUE TITLE
Navigation and application state

### ISSUE THREAD

**Issue by pwalsh** [openspending/fiscal-data-packager#20]
# Description

We need to allow the user to navigate back and forth across the application steps. We also want the user to have her data available, if she accidentally reloads the page.

# Tasks

* [x] Each step of the wizard needs to have its own route. The route can be used for managing state
* [x] Clicking on the "step buttons" will take the user to that step in the wizard, IF the user can reach that step with the current state of her data. Example: If a user is on step 2, she can go back to step one, change the file, and thereby reset the data of the wizard. Example: If a user is on step 4, and sees an error, she can go back to step two, change a concept, and then move forward to step 4 again and see the updated data
* [x] Likewise, if the user employs browser back/forward navigation, she should see the steps of the wizard, complete with any data
* [x] Functional tests for this

**Comment by pwalsh** [comment]
DONE.
