### ISSUE TITLE
Resource name and title

### ISSUE THREAD

**Issue by pwalsh** [openspending/fiscal-data-packager#21]
# Description

Resources should have reasonably useful names and titles. We have some logic in DataPackagist that does this, which may help here.

# Tasks

* [x] When a resource is added, do the following:
  * [x] Name it based on the file name, without the extension (file name should be able to be extracted from both local upload and from URL)
  * [x] Generate a titlecased title from the name 
* [x] unit tests

**Comment by pwalsh** [comment]
FIXED.
