### ISSUE TITLE
Step 2 Enhancements: Modeling actions

### ISSUE THREAD

**Issue by pwalsh** [openspending/fiscal-data-packager#23]
# Description

A set of interaction enhancements in order to be more accurate in creating a model from the user interface, as well as some small related tasks. This is the first part of the work of enhancing step 2. The work continues in #42, which is dedicated to the preview panel on the right side of the new UI mock.

![Step 2 Iteration 2](https://docs.google.com/drawings/d/1plpfWsyMpMmKCHREb58i-Vo8zDDF5kNQGnC4itAJNqo/pub?w=964&h=871)

# Tasks

* [x] Make the whole table smaller: reduced height on cells, reduced font size
* [x] More clearly delineate between data sample and the interaction elements for *describing* the package - in the mock we try to do that with a stronger colour for the describe header.. probably other options
* [x] In the description section
  * [x] Title gets slugified as the name of the dimension or the measure
  * [x] Concept: remove the `->` concepts (e.g.: `concept.id`)
  * [x] Concepts: have the following concepts
    * [x] DateTime
    * [x] Classification
    * [x] Activity
    * [x] Entity
    * [x] Location
  * [x] Some concepts have various *options* like currency, or `dimensionType` or `classficationType` - ensure that you identify these options so that the user can provide input based on the selected concept.
* [x] Narrative description of current state of model ("Selected concepts")
  * [x] Basic template for the section
  * [x] Show measures and their property selections to the list of measures
  * [x] Show dimensions and their property selections to the list of dimensions
  * [x] This is all bound to user actions when describing the data
* [x] "View this file" link opens target blank of file streamed via data pipes (http://datapipes.okfnlabs.org)
* [x] Tests

**Comment by pwalsh** [comment]
DONE!
