### ISSUE TITLE
Get real data for Region, Country and City inputs

### ISSUE THREAD

**Issue by pwalsh** [openspending/fiscal-data-packager#24]
# Description

We want to let the user select relevant regions, countries and cities, where each option is filtered down on the previous selection. For this we need an API. An [API has been started and is quite advanced here](https://github.com/openspending/cosmopolitan).

# Tasks

* [x] API at[ `http://os-cosmopolitan.herokuapp.com`](http://os-cosmopolitan.herokuapp.com)
  * can visit in browser and see how the responses look, as we have an HTML formatting
  * https://github.com/openspending/cosmopolitan#using-the-api have some instructions on how we can filter
* [x] Integrate with API to get this data
* [x] Use this API for the currency list
* [x] Customise the region, country and city inputs:
  * [x] City requires country value, country requires region value
  * [x] Change "Region" to "Continent"
  * [x] Once a "Continent" is selected, ensure that the "Country" list is filtered only for countries in that continent

**Comment by cecilaki** [comment]
On the Fiscal Data Packager, when user add a dataset, they're currently presented only a list of available countries ( for the moment only 2) - Should update the list to all countries. Leaving a blank field is too risky for typos in my sense, but being able to choose among a list seems a good option.

**Comment by pwalsh** [comment]
@cecilaki yes, that is what this issue is for, and that is why we are working on https://github.com/openspending/cosmopolitan

**Comment by cecilaki** [comment]
@pwalsh oh ok sorry - well then. great

**Comment by pwalsh** [comment]
DONE!
