### ISSUE TITLE
Step 1: Provide a CSV data source

### ISSUE THREAD

**Issue by pwalsh** [openspending/fiscal-data-packager#3]
# Description

Step 1 allows the user to add a CSV data source by local file or url. The basic interactions for this have been implemented in the existing `os-import` app, and can be seen here (with various bugs): http://os-import.herokuapp.com/create

The goals of this step are simple:

* Get the user's file
* When the file is added then
  * Check it is structurally valid (via the GoodTables API)
  * Infer a schema for the file (via the `jsontableschema.infer` method)
* After file has been checked, and inferred, then *allow* the user to move to the next step

# Tasks

Always refer back to the [spec/requirements document](https://docs.google.com/document/d/1FEiKb8B8xow8noNcJj78ZykMOD85eDvKf2zOcLZH1-o/edit#) for any background information.

## UI

All the basic templates for this step are implemented in the `os-import` code, so use this where possible to get a start on html and interactions.

* [x] Implement UI elements from existing `os-import` app for the following:
  * [x] Data file selector (local file or URL)
  * [x] Input when file has been added
    *  [x] ui elements when file is not structurally valid
    * [x] ui elements when file is structurally valid
    * [x] action at right of input to remove the file
    * [x] when file is structurally invalid, the modal that displays the errors in the file (error results from goodtables)
  * [x] State changes for the button to move to next step (state depends on status of file added)
* [x] **don't** bring over the name field and logic associated with it
* [x] The bar that shows the user where she is in process:
  * [x] Title: "Create a Fiscal Data Package"
  * [x] Subtitle: "Step 1: Provide your data"
* [x] The navigation icons that show the current step, and steps coming
  * [x] Step 1: Provide your data
  * [x] Step 2: Describe your data
  * [x] Step 3: Provide metadata
  * [x] Step 4: Confirm and download

## Data

* [x] init a base data package object
* [x] Function that handles file data flow (essentially identical to https://github.com/okfn/datapackagist/issues/178):
  * [x] When we have a structurally valid file and a schema inferred for it, then add as a resource to the data package, with various data on the resource, similar to https://github.com/okfn/datapackagist/issues/179

<img width="1280" alt="step1" src="https://cloud.githubusercontent.com/assets/791678/10722618/b71a0f7a-7bba-11e5-8f71-90e605936e15.png">

**Comment by pwalsh** [comment]
DONE.
