### ISSUE TITLE
Step 3: Provide additional metadata

### ISSUE THREAD

**Issue by pwalsh** [openspending/fiscal-data-packager#4]
# Description 

After the user has provided additional information to describe her data in step 2, we will collect additional metadata. This will be a basic set of forms of similar style to the elements in Step 1

# Tasks

Always refer back to the [spec/requirements document](https://docs.google.com/document/d/1FEiKb8B8xow8noNcJj78ZykMOD85eDvKf2zOcLZH1-o/edit#) for any background information.

* [x] **Title**: The name field that we removed from Step 1 now gets added as the first input in this form @kravets-levko make sure you *remove* the name field from step 1
* [x] **Short description**: A free text field for the user to describe the dataset
* [x] **Location**: A fieldset with the following fields. Can select all or none:
  * [x] **Region**: A list of all regions. Can select one or many. (@pwalsh can provide an example list. We'll hard code it for now but we may aim to break this into a service later)
  * [x] **Country**: A list of all countries. Can select one or many. (@pwalsh can provide an example list. We'll hard code it for now but we may aim to break this into a service later)
  * [x] **City**: Enter the name of a city
* [x] **Period**: Start date <-> End date
* [x] All of these data inputs are properties of the top-level DataPackage object
* [x] NEXT button as per previous steps - available when minimum requirements are met (Title is populated)
  * [x] At this step, you need to run `datapackage-validate` over the package, and display any errors if the package is not valid. Also note that **if** we have errors, they are errors in our logic somewhere, as the whole package has been created programmatically :)
* [x] Tests for their presence/absence on the Data Package object
* [x] Tests for form interaction

**Comment by pwalsh** [comment]
FIXED.
