### ISSUE TITLE
Step 2 Enhancements: Preview and "Possibilities" Panel

### ISSUE THREAD

**Issue by pwalsh** [openspending/fiscal-data-packager#42]
# Description

A set of interaction enhancements in order to be more accurate in creating a model from the user interface, as well as some small related tasks. This is the second part of the work of enhancing step 2. This work continues from #23, where we implemented the various modelling changes on the left side of the main interaction panel of the app.

![Step 2 Iteration 2](https://docs.google.com/drawings/d/1plpfWsyMpMmKCHREb58i-Vo8zDDF5kNQGnC4itAJNqo/pub?w=964&h=871)

# Tasks

* [x] Panel for Preview of data
  * [x] Heading and short intro text
  * [x] Generate list of possibilities
    * [x] Transaction Table
      * [x] A possibility when user has identified an "amount" concept
    * [x] Time series
      * [x] A possibility when user has identified an "amount" + "datetime" concept
    * [x] Treemap
      * [x] A possibility when user has identified an "amount" + "classification" concept
    * [x] Classification explorer
      * [x] A possibility when user has identified an "amount" + "classification" concept
    * [x] Multiple dimension agg.
      * [x] A possibility when user has identified an "amount" + multiple dimensions
  * [x] Generate Preview graph using sample of data and the possibility selected
    * [x] User click on possibility and the small graph is generated
    * [x] User can only click on "unlocked" possibilities (ones she has met the requirements for)
* [x] Tests

**Comment by pwalsh** [comment]
Note for later: Don't miss the `factor` option on the amount concepts, we have data that already needs it (BOOST paraguay).

**Comment by pwalsh** [comment]
DONE!
