### ISSUE TITLE
Step 2: Describe your data

### ISSUE THREAD

**Issue by pwalsh** [openspending/fiscal-data-packager#5]
# Tasks

Always refer back to the [spec/requirements document](https://docs.google.com/document/d/1FEiKb8B8xow8noNcJj78ZykMOD85eDvKf2zOcLZH1-o/edit#) for any background information.

* [x] Just use the basic header and footer we have. No other proper design at this stage. We just want to get the basic logic right
* [x] Represent a sample of the data back to the user, in a way that the user can relate to
  * [x] Take a sample of the headers, and first three lines of data from the file the user loaded, and display it as a table (we have tables like this in the Good Tables result set templates - you should be able to use this as a starting point).
    * [x] Implement a basic horizontal scroll if the table is beyond our content width
  * [x] Under each column in this data display, we have a set of input fields vertically aligned with each column. These are all user editable, and some are pre-populated with data we get as we read the file and inferred a schema
    * [x] **Title**: TitleCase version of the column name. if underscore in column name, split and turn into space (we have exactly this type of logic in DataPackagist)
      * [x] Is a property of the JSON Table Schema object for this field of the resource
    * [x] **Description**: A free text field for the user to enter a descriptive text
      * [x] Is a property of the JSON Table Schema object for this field of the resource
    * [x] **Data type**: A selector of different types (actually will be some type/format combinations but let's keep simple for now). The selected value is the type we detected for this field in the previous step's infer method
      * [x] Is a property of the JSON Table Schema object for this field of the resource
    * [x] **Concept**: Is a selector for the available "concepts" (measures and dimensions) in the Data Package
      * [x] Concepts are properties of the `mapping` object on the top-level DataPackage descriptor. [Example](http://fiscal.dataprotocols.org/spec/#mapping).
      * Available concepts (can be a hard coded list for now):
        * [x] Amount: `mapping.measures.amount`
        * [x] Date / Time: `mapping.date.properties.year`
        * [x] Classification: `mapping.classification.properties.id` (not an attribute group)
        * [x] Classification > ID: `mapping.classification.properties.id`
        * [x] Classification > Label: `mapping.classification.properties.label`
        * [x] Entity: `mapping.entity.properties.id` (not an attribute group)
        * [x] Entity > ID: `mapping.entity.properties.id`
        * [x] Entity > Label: `mapping.entity.properties.label`
      * [x] See the spec for how the mapping relates to fields on resources via the `source` property. Ensure you understand how this works, and sync with @rgrp and @pwalsh if unclear
  * [x] The user MUST map at least an Amount and a Date / Time in order to be "complete" at this step, and proceed to the next step
    *  [x] Like step one, button for NEXT, but only enabled when minimum conditions for this step are met 
  * [x] Unit tests for discrete logic (eg: updating mapping etc)
  * [x] Tests for their presence/absence of properties on the Data Package object in response to entered data
  * [x] Functional tests for UI interactions

# Mock UI

<img width="647" alt="screenshot 2015-09-07 22 55 16" src="https://cloud.githubusercontent.com/assets/791678/9722311/a0fe4fa8-55b3-11e5-9076-4498c28dc588.png">

**Comment by pwalsh** [comment]
@kravets-levko I saw that when I move forward from this step, you include the whole source of the CSV file in the `data` property of the resource. This is not necessary (and will kill the browser when we handle large resources #12). Instead, all we need is:

* `url`, if the source is a URL
* `path`, if the source is a file path (or just the file name, in our particular scenario)

**Comment by pwalsh** [comment]
FIXED.
